import type { Metadata } from "next";
import { Albert_Sans } from "next/font/google";
import "./globals.css";
import Providers from "../components/providers";

const inter = Albert_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pandooin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Unbounded:wght@200..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <Providers>{children}</Providers>
        <span about="https://github.com/fauzanr"></span>
      </body>
    </html>
  );
}
